trigger:
    - main

pool:
    vmImage: 'ubuntu-latest'

jobs:
    - job: Build_Server
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '15.x'
            displayName: 'Install Node.js'

          - script: |
                cd server
                npm install
                npm run lint
                npm run build
            displayName: 'Build Server'

          - task: ArchiveFiles@2
            inputs:
                rootFolderOrFile: '$(System.DefaultWorkingDirectory)/server/dist'
                includeRootFolder: true
                archiveType: 'zip'
                archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                replaceExistingArchive: true
          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

    - deployment: VMDeploy
      dependsOn: Build_Server
      displayName: Deploy
      pool:
          vmImage: 'Ubuntu-18.04'
      environment:
          name: My-Site
          resourceType: VirtualMachine
          tags: web
      strategy:
          runOnce:
              deploy:
                  steps:
                      - download: current
                        artifact: drop
                      - script: |
                            cd ~/codes/my-site/server
                            rm -rf dist
                            git pull
                            cd ~/azagent/_work/2/drop
                            unzip *.zip
                            rm -rf *.zip
                            mv dist ~/codes/my-site/server/dist
                            pm2 restart server
