# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
    - main

pool:
    vmImage: 'ubuntu-20.04'

jobs:
    - job: Build
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '15.x'
            displayName: 'Install Node.js'

          - script: |
                mkdir temp
                cd server
                npm install
                npm run build
                mv dist ../temp
                mv build ../temp
            displayName: 'Build Projects'

          - task: ArchiveFiles@2
            inputs:
                rootFolderOrFile: '$(System.DefaultWorkingDirectory)/temp'
                includeRootFolder: true
                archiveType: 'zip'
                archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                replaceExistingArchive: true
          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

    - deployment: VMDeploy
      dependsOn: Build
      displayName: Deploy
      pool:
          vmImage: 'Ubuntu-20.04'
      environment:
          name: web
          resourceType: VirtualMachine
          tags: web
      strategy:
          runOnce:
              deploy:
                  steps:
                      - script: |
                            cd $(Build.ArtifactStagingDirectory)
                            cd ../drop
                            rm -rf *
                            cd ~/my-site/server
                            rm -rf dist
                      - download: current
                        artifact: drop
                      - script: |
                            cd $(Build.ArtifactStagingDirectory)
                            cd ../drop
                            unzip $(Build.BuildId).zip
                            cd temp
                            mv dist ~/my-site/server/dist
                            cd ~/my-site/server
                            npm i
                            npm run redeploy
